### ISSUE TITLE
newAccount Trigger / Id missing

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#11]
The latest version of this component doesn't query the attribute Id from SalesForce. V3 of the component still contains the Id attribute. 

This issue is directly connected with the last commit: #587b45d (587b45de9f68b050c5d500f4f6826c97cba3ebea) by @zubairov .

This is the outcome sample in which the above mention ID is missing:
```javascript
{
"SLAExpirationDate__c": "2015-10-05",
"SLASerialNumber__c": "3479",
"UpsellOpportunity__c": "No",
"NumberofLocations__c": 34,
"Active__c": "Yes",
"SLA__c": "Platinum",
"CustomerPriority__c": "High",
"SicDesc": null,
"YearStarted": null,
"NaicsDesc": null,
"NaicsCode": null,
"Tradestyle": null,
"DunsNumber": null,
"AccountSource": null,
"Jigsaw": null,
"Site": null,
"Rating": null,
"Description": null,
"TickerSymbol": "UOS",
"Ownership": "Public",
"NumberOfEmployees": 24000,
"AnnualRevenue": null,
"Industry": "Energy",
"Sic": "4437",
"Website": "http://www.uos.com",
"AccountNumber": "CD355119-A",
"Fax": "44 191 4956620",
"Phone": "44 191 4956203",
"ShippingCountry": null,
"ShippingPostalCode": null,
"ShippingState": null,
"ShippingCity": null,
"ShippingStreet": "Kings Park, 17th Avenue, Team Valley Trading Estate,\nGateshead, Tyne and Wear NE26 3HS\nUnited Kingdom",
"BillingCountry": null,
"BillingPostalCode": null,
"BillingState": "UK",
"BillingCity": null,
"BillingStreet": "Kings Park, 17th Avenue, Team Valley Trading Estate,\nGateshead, Tyne and Wear NE26 3HS\nUnited Kingdom",
"Type": "Customer – Direct",
"Name": "United Oil & Gas, UK",
"attributes": {
"url": "/services/data/v25.0/sobjects/Account/0010Y000002UR9QQAW",
"type": "Account"
}
}
```
![bug.png](https://images.zenhubusercontent.com/5979b59561b4ca3b0a75e342/101297ae-805e-4b23-80cb-7035e5f72c00)

**Comment by zubairov** [comment]
I'm unfortunately full day in meetings toady and tomorrow @drobiazko could you support me on it?

**Comment by khanzadyan** [comment]
@zubairov I've created the issue here just because we are moving away from Jira. I'm not sure that this is a critical and needs to be addressed during this or next week.

**Comment by A3a3e1** [comment]
@khanzadyan Seems like the latest version API does not return this value. It can be added with some additional trick (request).
Should it be done?

**Comment by ShkarupaNick** [comment]
@A3a3e1  Issue was fixed in issue #27.
@stas-fomenko, can you check it?

**Comment by stas-fomenko** [comment]
fix is tested

**Comment by stas-fomenko** [comment]
not yet, most probably it will be deployed on Nov 14
