### ISSUE TITLE
Component Get New and Updated Objects Polling Trigger doesn't allow for '__r' fields

### ISSUE THREAD

**Issue by christianjosephvarriale** [elasticio/salesforce-component#126]
## Description
When performing a SOQL query, a child object will have access to it's parent via a `__r` or relationship field. In theory, one should be able to then access any field value of the parent related object, for example parent__r.Name. Currently, our component can only support this through the `Query` action or `Lookup` action, but it's not present through the `Get New and Updated Objects Polling` trigger. This was discovered by one of our clients and was a major roadblock for them. 

## Expected Functionality
![Screenshot from 2020-03-12 11-42-54](https://user-images.githubusercontent.com/37720685/76523378-9f499f00-6468-11ea-99af-fffe24e93488.png)

We can see in the above image that the `Contract__r` field is present and is rendered as an object. This image is an illustration of the current functionality available using the lookup component and our current PS org. By default, if the `include referenced objects` is not specified then the Id of the lookup record is returned.

1. Add a `include referenced objects` field on the `Get New and Updated Objects Polling` Trigger which will allow the integrator to specify `__r` fields of their choice

**Comment by jhorbulyk** [comment]
@christianjosephvarriale Can you add steps to reproduce?  (i.e. Identify an object an a field that is not showing up that we expect to show up?)
