### ISSUE TITLE
1k limitation

### ISSUE THREAD

**Issue by vdidushko** [elasticio/salesforce-component#131]
Our customer from PDI has a flow that inserts data from Salesforce to Redshift. He has around 8k records, however, the flow goes to sleep after importing 1k records.

![screenshot_68](https://user-images.githubusercontent.com/48764578/80471882-b1b26600-894c-11ea-85ab-dff89ad8a709.png)

AFAIK this might be related to :

```https://github.com/elasticio/salesforce-component/blob/65c472a9fcfaa3b1564e2c6f2a3f5877df53820d/lib/actions/query.js#L8```

**Comment by kirill-levitskiy** [comment]
The bug was fixed and update is available in the master branch
