### ISSUE TITLE
Rewrite to use authclient (new platform functionality)

### ISSUE THREAD

**Issue by umkaline** [elasticio/salesforce-component#147]
Use new Auth-clients platform functionality to overcome all current oAuth2 limitations (as a token expiry).

**BEFORE TAKE THIS TASK:**
Need to be investigated the behavior of rendering creds view. 
Seems that after deploying a new component version new creds view would be rendered even for components with chosen 'old' versions, so user cannot modify or fix already existing 'old' creds, and would need to create a new one and fix flows.
If this statement is correct then pushing Salesforce 2.0.0 to the same platform repo is not a good option to release the component and further development strategy need to be discussed (to push it to a new repo, request a platform fix etc.)

**Additional Info:**
1. It will be a new component's major version 2.0.0 and no backward compatibility expected, so flow may be broken in case if the selected component version is `latest`.
2. Deprecated triggers/actions should be deleted and flow will be broken in case if the selected component version is `latest`.

**UPD**
1. As deprecated triggers/actions will be removed we need to check if there are any flows of real customers with deprecated triggers/actions that have `latest` version, task for support: https://github.com/elasticio/support/issues/476.

**Comment by shulkaolka** [comment]
> BEFORE TAKE THIS TASK:
Need to be investigated the behavior of rendering creds view.
Seems that after deploying a new component version new creds view would be rendered even for components with chosen 'old' versions, so user cannot modify or fix already existing 'old' creds, and would need to create a new one and fix flows.
If this statement is correct then pushing Salesforce 2.0.0 to the same platform repo is not a good option to release the component and further development strategy need to be discussed (to push it to a new repo, request a platform fix etc.)

In current version it is used `viewClass`: `OAuthFieldView` for oauth field:
![image.png](https://images.zenhubusercontent.com/5bbdbe5852317e2a55ad20be/93563038-a873-41da-9873-660f0f4afc9b)
If it is used `viewClass`: `HTTPAuthView` and `"authClientTypes": ["oauth2"]` and deployed new version to the same repo for previous version of component it is impossible to create new credentials or edit old one, credentials window looks like:
![image.png](https://images.zenhubusercontent.com/5bbdbe5852317e2a55ad20be/f2dc3a48-d623-4bcb-83b9-dbf3d4b97610)

**Comment by shulkaolka** [comment]
This issue depends on platform issues:
https://github.com/elasticio/elasticio/issues/4517 - already fixed
https://github.com/elasticio/elasticio/issues/4527 - in process

**Comment by stas-fomenko** [comment]
Release blocked by https://github.com/elasticio/support/issues/476
