### ISSUE TITLE
When Inserting an Object, we should be able to provide values for parent Objects

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/salesforce-component#15]

**Comment by zubairov** [comment]
I believe this can be done in two actions - first finding the parent object, second inserting the child object with the parent ID set

**Comment by zubairov** [comment]
finding the parent object could be done via `SOQL Action`, passing data around could be done via pass-though

**Comment by jhorbulyk** [comment]
Currently, we do not generate inputs for linked IDs based on the metadata:   https://github.com/elasticio/salesforce-component/blob/master/lib/helpers/metadata.js#L62-L64
