### ISSUE TITLE
Caching in SOQL Query

### ISSUE THREAD

**Issue by zubairov** [elasticio/salesforce-component#20]
Would be great to cache resuts of the SOQL query, however we need to consider following aspects:

- [ ] One should be able to enable/disable caching
- [ ] Some SOQL results can be very large, but we coudl initially limit the number of rows that will be cached
- [ ] Two SOQL queries should be considered equal only if the are letter-by-letter equal

**Comment by jhorbulyk** [comment]
I have the following questions:
* Is the goal to be able to cache arbitrary SOQL queries or is the goal to be able to cache `lookupObjectByField` queries?
* Where would this information be cached?  Are we going to assume that the component might be part of a real time flow and thus we would cache information in memory or are we looking to cache lookup results in the component snapshot?

**Comment by zubairov** [comment]
Yes, agree actually the caching would be highly benificial for `lookup` action, not for the generic SOQL query.
To the caching where question - we should just use component's memory, my idea was more or less a cache that would use `WeakMap` and cache data may be for couple of seconds or max a minute, not more.
