### ISSUE TITLE
Error with retrieving sample from Salesforce

### ISSUE THREAD

**Issue by luzhok** [elasticio/salesforce-component#21]
STR:
1. Go to the flow:
https://app-popeye.elastic.io/o/573dd76962436c349f000003/#/designer/5a33d96a9e85bb000720b8ab
2. Go to the latest step - Step2
3. Press the button "Retrieve Sample"
AR: there is Error! - see the screen
![image](https://user-images.githubusercontent.com/32069340/34162859-d90e9540-e4dd-11e7-8c05-e752966f7f04.png)
some times retrieve sample is passed, but it is very rarely. Almost always it is finished with error.
The same problem is actual on the Flint.

**Comment by HannaTrotsenko** [comment]
Maybe it will help:
The Request Headers of starting Generate Sample debug task:
- success generated in previous step ```Content-Length:7513```
- error in next step ```Content-Length: 31915```

The pass through grows up more than 4 times

**Comment by A3a3e1** [comment]
Maybe because of lack of memory. Estimated for initial investigation

**Comment by luzhok** [comment]
@A3a3e1 it isn't actual anymore. I closed the issue. Thanks
