### ISSUE TITLE
Error : "No Metadata Found" should not prevent polling

### ISSUE THREAD

**Issue by zubairov** [elasticio/salesforce-component#25]
![image](https://user-images.githubusercontent.com/56208/37780121-5f28ed48-2dee-11e8-9271-8ebc8908b0ff.png)

**Comment by A3a3e1** [comment]
Is not clear whether it can be fixed or no (and how). So estimation includes initial investigation

**Comment by A3a3e1** [comment]
@zubairov Our understanding of the issue:
'No out metadata found to create select fields from' message appears when something is wrong with Salesforce API which is responsible for metadata providing.
Select query for the polling trigger is being built from the metadata retrieved from Salesforce API.
Hence, it's impossible to create a query without metadata and the trigger can't work in this case.
So don't see any sense in this issue.
Any thoughts?

**Comment by ShkarupaNick** [comment]
Trigger code was refactored.
used construction
```js
await conn.sobject(cfg.object)
        .select('*')
        .where(`LastModifiedDate > ${snapshot}`)
        .execute({maxFetch : 100000}, processResults);
```
but function `select` calls describe api  method too.
So - need more investigation:

Workaround:
get Id of each changed entity and fetch each object by internalId using `retrieve`
But need investigation about api calls which makes `retrieve` function

**Comment by ShkarupaNick** [comment]
Unfortunately, jsfoce hasn`t the opportunity to select objects without a list of object fields. So we should ask metadata of objects before query to sobject API.

Selecting all objects by id,s  is a very expensive operation for the component. 

As a workaround, I can suggest implementing a new smart trigger. 
the main idea: trigger subscribes to changes during flow starting. 

we can use [Salesforce Tooling API](https://jsforce.github.io/document/#tooling-api) for it.

Using this API we can deploy our custom trigger code, which can call our webhook endpoint after object create/change event.

And also we can delete this trigger code during flows stopping.

**Comment by ShkarupaNick** [comment]
Example of salesforce ApexTrigger:
https://blog.jeffdouglas.com/2009/03/16/restful-web-service-callout-using-post/
