### ISSUE TITLE
Error message is shown in Action: Query after retrieve sample try when object is not found

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/salesforce-component#40]
**Description:** Error message `Error! Sorry! The component did not provide any sample data.`  is shown in Action: Query after retrieve sample try when object is not found

**Preconditions:** 
Use PS Salesforce creds

**STR:**
1. Create flow Timer -> SF
2. Choose  Action: Query in SF.
3. Input query that will not find any object (for example: `"SELECT ID, Name from Contact where Name like 'tttt%'"` )
4. Click on "Retrieve Sample" button
5. See error message.

AR: Error message `Error! Sorry! The component did not provide any sample data.`  is shown in Action: Query after retrieve sample try when object is not found

ER: When Lookup failed (we were not able to find any parent object), In this case Lookup action should emit a single message with empty body.

**Comment by stas-fomenko** [comment]
@jhorbulyk yea, I pasted it from [here](https://github.com/elasticio/salesforce-component/issues/16), but actually missed date of comment: `20 Nov 2017`, what was much before our components meetings. @zubairov what do you think? ☝️ what do we want component to do if query did not find any object?

**Comment by jhorbulyk** [comment]
Related to component standards, the Lookup Objects (plural) action describes the concept of `fetchAll` mode vs `emitIndividually` mode.  (It also describes `fetchPage` that likely isn't applicable to this case).  It may make sense to add these two modes to the action which will then have a clearer definition for the no matching results case.

**Comment by A3a3e1** [comment]
It is a not standardized Query action. Not a standardized Lookup

**Comment by jhorbulyk** [comment]
> It is a not standardized Query action. Not a standardized Lookup

@A3a3e1 Correct.  The idea is applicable right?

**Comment by stas-fomenko** [comment]
may be implemented as in Exact-Online-component -> Action: Lookup Objects

**Comment by stas-fomenko** [comment]
**DoD**

**Component development prerequisites:**

- [ ] Development team has all needed requirements
- [ ] Access to the needed service with all needed permissions is granted
- [ ] No open tasks that could block Component development process
- [ ] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [ ] Component architecture should be discussed and approved before start coding

**Development:**

- [ ] Code is written and formatted in accordance with the Styling guide
- [ ] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [ ] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [ ] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [ ] Documentation (README.md file in the Github) is 100% ready
- [ ] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated
