### ISSUE TITLE
Update the Salesforce API version to V44 or any latest one

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#43]
This is not particularly a big issue. However, the supported version is V39 which us from Spring 2017 which lucks additional functionality like a proper support for `custom objects` and `custom tables` (?). These features were added in the later versions.

It might be a good idea to extend the functionality of this component to include above-mentioned objects by upgrading to V44 (Winter 2019). 

Below are the observations from one customer:

> 1. SOQL action not fetching some Salesforce columns and throwing the invalid column error.
> 2. new other object action not fetching the custom tables.

**Comment by stas-fomenko** [comment]
**DoD**

**Component development prerequisites:**

- [ ] Development team has all needed requirements
- [ ] Access to the needed service with all needed permissions is granted
- [ ] No open tasks that could block Component development process
- [ ] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [ ] Component architecture should be discussed and approved before start coding

**Development:**

- [ ] Code is written and formatted in accordance with the Styling guide
- [ ] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [ ] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [ ] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [ ] Documentation (README.md file in the Github) is 100% ready
- [ ] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated
