### ISSUE TITLE
Salesforce component not picking the more the 10 K records from the module

### ISSUE THREAD

**Issue by ankitmagicsoft** [elasticio/salesforce-component#47]
My salesforce account has 86K records but when I'm running the flow then it's only picking 10K records from there.

**steps to reproduce**
Select any object which has more the 10K records from the salesforce component using the "New other objects" options and creates the flow and then runs it. It will pick up only 10K records from that module only.

**Actual Result **: Not picking the more the 10 K records from the module.

**Expected Result** It should pick up all the records from the salesforce component.

![image](https://user-images.githubusercontent.com/38919810/52576801-dce38f00-2e46-11e9-860a-111e69254082.png)

**Comment by zubairov** [comment]
Reason for this:

https://github.com/elasticio/salesforce-component/blob/master/lib/entry.js#L107

We need paging

**Comment by ShkarupaNick** [comment]
will be implemented in issue #50

**Comment by ShkarupaNick** [comment]
Estimated for investigation of better way for implementation

**Comment by shulkaolka** [comment]
**CDoD**

**Development:**
- [x] Code is written and formatted in accordance with the Styling guide.
- [x] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests.
- [x] Triggers/actions comply with OIH patterns.
- [x] Documentation (README.md file in the Github) is 100% ready. 
- [x] Component code is covered with integration tests.
- [x] Component code is reviewed and fixed, if needed.
- [ ] CI is set up
- [ ] Sprint review preparation is finished (build demo flow is built)

**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] All the development branches are reviewed and merged into master
- [ ] Component is deployed to the production stage (app.elastic.io) or/and other required stage.
  - Smoke test is finished there.
  - Component has a proper access level
- [ ] Release notes are done. 
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated
