### ISSUE TITLE
Add Trigger to Subscribe to Salesforce CommetD Event Bus

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/salesforce-component#49]
*No Applicable OIH Guideline*

Salesforce implements a streaming API.  One can use this API to subscribe to events from Salesforce's internal bus mecahnism.  The streaming API is implemented using the CometD protocol. For more info see:
* https://stackoverflow.com/questions/27317774/what-is-cometd-why-it-is-used-and-how-to-work-on-that
* https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/BayeauxProtocolAndCometD.htm
* https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_intro_emp.htm

The streaming API is supported by JSForce out of the box. https://jsforce.github.io/document/#streaming-api 

The component performing the streaming would potentially require a realtime flow or at least a flow where the sailor self-kill feature is disabled.  See https://github.com/elasticio/platform/issues/645 and https://github.com/elasticio/salesforce-stream-component

The authentication mechanism for this API is the same as all other Salesforce APIs.  The config fields should be all the details to indicate what event types should be subscribed to.

**Comment by zubairov** [comment]
@jhorbulyk would be beneficial if you could describe configuration options you want to see on this trigger, for example pre-filtering of the event types or any other type of config?

**Comment by jhorbulyk** [comment]
I've read through the docs but at the moment I don't have a clear enough understanding of all of the moving pieces to answer that question.

**Comment by zubairov** [comment]
@jhorbulyk do you think you have more information now so that enhancement request could be more specific?

**Comment by jhorbulyk** [comment]
There are two types of CommetD eventing: push topics and platform events.  Platform events are the higher priority.  Each platform events exist as a type of Salesforce object and the subscription url is `/events/<nameofevent>__e>`

**Comment by ShkarupaNick** [comment]
will be added new polling trigger, which will work only for realtime flow:
`Subscribe to platform events (REALTIME FLOWS ONLY)`

**Comment by stas-fomenko** [comment]
**CDoD**

**Development:**
- [ ] Code is written and formatted in accordance with the Styling guide.
- [ ] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests.
- [ ] Triggers/actions comply with OIH patterns.
- [ ] Documentation (README.md file in the Github) is 100% ready. 
- [ ] Component code is covered with integration tests.
- [ ] Component code is reviewed and fixed, if needed.
- [ ] CI is set up
- [ ] Sprint review preparation is finished (build demo flow is built)

**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] All the development branches are reviewed and merged into master
- [ ] Component is deployed to the production stage (app.elastic.io) or/and other required stage.
  - Smoke test is finished there.
  - Component has a proper access level
- [ ] Release notes are done. 
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated
