### ISSUE TITLE
Add paging to Salesforce triggers

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#50]
During the initial sync of data from Salesforce to some third party API the component is trying to fetch as many records as possible till < 10K limit. This can potentially create a problematic situation during the sync process by hitting the queue processing limits.

Please add a paging capability to all trigger functions if possible. Ideally, it would be nice to have an ability to fetch by 100, 500 or 1000 records per call. This could potentially provide a solution for the #47 issue as well.

**Comment by zubairov** [comment]
> Please add a paging capability to all trigger functions if possible. Ideally, it would be nice to have an ability to fetch by 100, 500 or 1000 records per call. This could potentially provide a solution for the #47 issue as well.

We should adhere to OIH standard behavior here

**Comment by jhorbulyk** [comment]
> We should adhere to OIH standard behavior here

@zubairov There is an OIH standard for page size but nothing for "singlePageOfResults" yet.  I expect to see that added soon but I suspect the process of expanding these behavoirs will be discussed in that meeting.

**Comment by shulkaolka** [comment]
**CDoD**

**Development:**
- [x] Code is written and formatted in accordance with the Styling guide.
- [x] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests.
- [x] Triggers/actions comply with OIH patterns.
- [x] Documentation (README.md file in the Github) is 100% ready. 
- [x] Component code is covered with integration tests.
- [x] Component code is reviewed and fixed, if needed.
- [ ] CI is set up
- [ ] Sprint review preparation is finished (build demo flow is built)

**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] All the development branches are reviewed and merged into master
- [ ] Component is deployed to the production stage (app.elastic.io) or/and other required stage.
  - Smoke test is finished there.
  - Component has a proper access level
- [ ] Release notes are done. 
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated

**Comment by zubairov** [comment]
@stas-fomenko can we close this one?
