### ISSUE TITLE
Write OIH Compliant "Lookup Object (at most 1)" Iteration 2 Action

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/salesforce-component#55]
[OIH standards](https://github.com/openintegrationhub/Connectors/blob/master/Adapters/AdapterBehaviorStandardization/StandardizedActionsAndTriggers.md#iteration-2-lookup-object-by-unique-criteria)

There should be an action `Lookup Object (at most 1)` that adheres to the OIH standard for Salesforce.  It likely makes sense to depricate the existing lookup behavior.   It also makes sense to use the latest API version.

Iteration 1 (by ID only) is insufficient.  Iteration 2 (by unique criteria) is required.  It appears as though it is possible to write business rules that enforce uniqueness on one or more fields, but it is not possible to learn those rules dynamically.  There are some db level settings to enforce uniqueness that can be read.

Suggestions for config fields:
* Object Type (dynamic dropdown): All `sobjects` in `describeGlobal` where `searchable` is `true`.  In the config object, the key should be `name` and the value should be `${sobject.label} (${sobject.name})`.
* Type Of Search (static dropdown): Two values: `Unique Fields`, `All Fields`
* Field to Search (dynamic dropdown): If `All Fields` then all fields on the selected object.  If `Unique Fields` all fields on the selected object where `type` is `id` or `unique` is `true`.  In the config object, the key should be `name` and the value should be `${sobject.label} (${sobject.name})`.
* Allow Criteria to be omitted (dropdown/checkbox: yes/no): As the OIH standard describes
* Allow zero results (dropdown/checkbox: yes/no): As the OIH standard describes

All fields on the matched object should be returned.  At this point in time we do not need to worry about expanding parent or child linked objects.  We may need to come back to this in the future.

**Comment by shulkaolka** [comment]
**CDoD**

**Development:**
- [x] Code is written and formatted in accordance with the Styling guide.
- [x] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [x] Code is covered with unit tests.
- [x] Triggers/actions comply with OIH patterns.
- [x] Documentation (README.md file in the Github) is 100% ready. 
- [x] Component code is covered with integration tests.
- [x] Component code is reviewed and fixed, if needed.
- [ ] CI is set up
- [ ] Sprint review preparation is finished (build demo flow is built)

**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] All the development branches are reviewed and merged into master
- [ ] Component is deployed to the production stage (app.elastic.io) or/and other required stage.
  - Smoke test is finished there.
  - Component has a proper access level
- [ ] Release notes are done. 
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated
