### ISSUE TITLE
Add ability to send PDF documents back to Salesforce

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#57]
Salesforce connector improvement

As the client is creating protocols of a customer appointment, it would be nice if the document as a `pdf` can be sent back to the appropriate case, lead, contact and account (not sure about tasks, events and notes).

Therefore, it should be possible to transfer the `pdf` as an attachment to Salesforce.

**Comment by shulkaolka** [comment]
https://github.com/jsforce/jsforce/issues/43 example of a solution

**Comment by juhrmacher** [comment]
[https://app.zenhub.com/files/41149571/105cdff8-247d-4ccb-96a1-6afb79296ae7/download](https://app.zenhub.com/files/41149571/105cdff8-247d-4ccb-96a1-6afb79296ae7/download)
