### ISSUE TITLE
Salesforce component should be able to receive new acess tokens when retrieving platform events

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/salesforce-component#65]
Steps to Reproduce (not sure if fully accurate):
1. Create a realtime flow to listen to salesforce platform events
2. Configure a valid credential.
3. Start the flow.
4. Execute another flow where the access token is refreshed.
4. Wait more than an hour for the access token in the platform event  to expire.
5. Observe that after the first hour, the flow will no longer receive platform events as the tokens are no longer valid.

**Comment by kirill-levitskiy** [comment]
@jhorbulyk additional question:
I'm not sure that I correctly understood the 4th step:
`4. Execute another flow where the access token is refreshed.`

Is it enough to create a copy of the same flow and run both of them to observe the issue?

**Comment by jhorbulyk** [comment]
> Is it enough to create a copy of the same flow and run both of them to observe the issue?

Likely.  I haven't fully identified the steps needed to reproduce.

**Comment by zubairov** [comment]
Apparently, a similar issue that we run into when doing the Exact Online. Maybe worth speak to platform guys if they have some progress there?

@drobiazko thoughts?

**Comment by jhorbulyk** [comment]
I feel as though a major contributing issue is lack of proper secrets service in the platform.  Is there any update on when we expect to be able to import the OIH version into our platform (or provide a similar microservice with similar features)?  Has such an issue been written up?

**Comment by kirill-levitskiy** [comment]
The issue is not reproducible with provided list of steps

**Comment by jhorbulyk** [comment]
Suprisingly, it works if you leave the event bus flow on.  The only problems appear if you turn off the flow that consumes things from the event bus.
