### ISSUE TITLE
Create unit tests for existing functionality that uncovered by unit tests 

### ISSUE THREAD

**Issue by shulkaolka** [elasticio/salesforce-component#75]
As continue of #18 it is needed to cover by unit-tests existing functionality:
1. helpers/http-utils
2. helpers/oauth-utils
3. helpers/metadataLoader
4. all actions (that isn't deprecated)

**Comment by stas-fomenko** [comment]
@ZainNoor99 as the current task does not require a QA stage (only tested if the build is successful) it could be merged into master and moved to `Stage` on Board
