### ISSUE TITLE
difference in samples retrieved based on steps in flow

### ISSUE THREAD

**Issue by vdidushko** [elasticio/salesforce-component#96]
Scenario:

You have Webhook as 1st step, Code as 2nd and Salesforce as the 3rd step.

![3steps](https://user-images.githubusercontent.com/48764578/70537560-503e5600-1b69-11ea-87c7-0032a38eaa52.png)

And you have Query:
![query](https://user-images.githubusercontent.com/48764578/70537634-72d06f00-1b69-11ea-91af-3b107c6aac21.png)

Sample 1 and Sample 2 are identical. 
![sample1](https://user-images.githubusercontent.com/48764578/70537797-baef9180-1b69-11ea-8ba4-9094461c2e3d.png)
![sample2](https://user-images.githubusercontent.com/48764578/70537809-be831880-1b69-11ea-8f0d-477e237ca9c1.png)

But if you have Salesforce as the 1st step in your flow, you are going to get different samples.
![sales1st](https://user-images.githubusercontent.com/48764578/70538022-16ba1a80-1b6a-11ea-8a55-199cc644d34c.png)

Query is the same:
![query2](https://user-images.githubusercontent.com/48764578/70538043-1f125580-1b6a-11ea-8487-0f76b3eaa602.png)

Different samples received:
![sample3](https://user-images.githubusercontent.com/48764578/70538157-4ff28a80-1b6a-11ea-9244-1769ff7f1bd6.png)
![sample4](https://user-images.githubusercontent.com/48764578/70538166-53861180-1b6a-11ea-8033-c532f86f09bf.png)

**Comment by vdidushko** [comment]
The latest version of the component was used.

**Comment by jhorbulyk** [comment]
What is the difference in the samples?

**Comment by vdidushko** [comment]
The difference is that there are different people shown in Sample 1 and Sample 2 in case when Salesforce is the first step.
