### ISSUE TITLE
Salesforce. Update component to new sailor version / use new logger functionality / dockerize

### ISSUE THREAD

**Issue by shulkaolka** [elasticio/salesforce-component#98]
**DoD**
**Development:**
- [x] use new logger
- [x] component should be dockerised, add: "buildType":"docker" line into component.json
- [x] sailor version is changed from 2.5.1 to 2.5.4
- [x] CHANGELOG.md is updated
**QA:**
- [ ] Smoke test is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or another required stage

**Comment by A3a3e1** [comment]
**Smoke test checklist**
- [ ] Push to platform
- [ ] Retrieve sample
- [ ] Retrieve sample on LA (if possible)
- [ ] Run keen flow
- [ ] Run realtime flow
- [ ] Create valid creds in the flow
- [ ] Create valid creds in credentials itself

branch: `sprint-31-sailor-logger-update`

**Comment by stas-fomenko** [comment]
regression is needed

**Comment by stas-fomenko** [comment]
@shulkaolka 
Please take a look at the issues list:
https://docs.google.com/spreadsheets/d/1tmNkVr30Yk0oQx4EeEiceTzSW19_jnPrQgQY1iZnKco/edit#gid=0
